### ISSUE TITLE
Ferdigstilling av openAPI-spesifikasjon enhetsregisteret

### ISSUE THREAD

**Issue by TorjusNetcompany** [brreg/openAPI#6]
Hei!
Kjempebra med en teknisk spesifikasjon. Men det ser kanskje ut som at den ikke ble helt ferdigstilt?
Ser blant annet dette i `enhetsregisteret.yml`:
"Teknisk beskrivelse av REST-tjenestene i Åpne Data fra Enhetsregisteret - Work in progress"
Som antyder at arbeidet aldri ble helt ferdig.

For flere av operasjonene mangler det også en returverdig, feks `hentUnderenhet`, `listEnheter`, `listTjenester`, `listUnderenheter` og alle endepunkter som har noe med oppdateringer å gjøre.
Er det planlagt å ferdigstille denne dokumentasjonen?

Dette hadde vært veldig nyttig for oss (Oslo kommune - ITAS) siden vi holder på med en integrasjon mot brreg for øyeblikket.
Takk for all hjelp eller svar på dette.

**Comment by torjuskd** [comment]
Lagde en pr som forbedrer spesifikasjonen betraktelig, et steg videre til en ferdig openapi definisjon av apiet. https://github.com/brreg/openAPI/pull/7
